### PR TITLE
provide minimal IAM policy for creating FargateCluster

### PR DESCRIPTION
**Pull request by rsignell-usgs**

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks for this @rsignell-usgs!

I've moved this further down in the docs and also added a second example for folks who want to specify their own iam roles, subnets, etc which should require fewer permissions.

**Comment by jacobtomlinson** [comment]
Closed #49

**Comment by jkmacc-LANL** [comment]
This is awesome!  Thanks, @rsignell-usgs!  @jacobtomlinson, what is meant by “specify ... themselves” are In the minimal example?  I’m anticipating that many folks looking here for a quick zero-to-dask solution  (myself included) may not know what this means (myself included).

**Comment by jacobtomlinson** [comment]
@jkmacc-LANL are you referring to these lines?

> To create a ``FargateCluster`` the cluster manager will need to various AWS resources ranging from IAM roles to VPCs to ECS tasks. Depending on your use case you may want the cluster to create all of these for you, or you may wish to specify them youself ahead of time.

**Comment by jkmacc-LANL** [comment]
@jacobtomlinson I'm just thinking that, without visiting with you and @rsignell-usgs at the Dask workshop last month, I wouldn't know what to do with that block of JSON, even though you've specified it for me.  Is there a good resource or link you use to understand IAM policies and how to apply them, particularly for users of this library?

**Comment by jacobtomlinson** [comment]
@jkmacc-LANL documentation [like this](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html) should be useful to you. Perhaps we should also link that page form the documentation, although it was the top hit for "creating IAM policies" on Google.

I have made some assumptions that it would be good to check though:

- Individuals signing up for their own AWS account will likely be using the default administrator role with all of the required permissions.
- Institutions providing accounts to staff will likely have a process for requesting permissions. They will probably appreciate being provided a JSON policy like this.
- Folks setting up their own multi-user systems like Pangeo should have some understanding of AWS and should recognise an IAM policy and what to do with it.

These assumptions may be wrong, or I may have missed some use cases. Any input and feedback would be much appreciated!

**Pull request merged**
