### PR TITLE
Updates to AzureMLCluster

### PR DESCRIPTION
**Pull request by lostmygithubaccount**
- `environment_definition` -> `environment` (breaking API change, probably not allowed?)
- remove datastores
- `Estimator` -> `ScriptRunConfig` and necessary changes to inputs, removing dependency on azureml.train

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks for this. I'm not too worried about the breaking change at this point. This API is still a little in flux.

**Comment by nickeubank** [comment]
Any chance this addresses #150 ?

**Comment by lostmygithubaccount** [comment]
don't think so - commented over there - I also think this PR needs:

- [ ] testing
- [ ] update documentation
- [ ] other edits?

**Comment by lostmygithubaccount** [comment]
@jacobtomlinson would it be possible to setup an Azure ML Workspace so we could do some automated testing with GitHub actions?

**Comment by jacobtomlinson** [comment]
@lostmygithubaccount I've been thinking about better testing today actually.

The problem is that we would need to store credentials in GitHub secrets which are not available in PRs (and for good reason). Do you have thoughts on a solution to this? I'm looking into some kind of "ok to test" workflow now but not finding much.

**Comment by lostmygithubaccount** [comment]
we have the same problem in Azure/azureml-examples - it does work on PRs for *branches*, just not *forks* - so if you're comfortable giving contributors the ability to create branches that could help

**Comment by jacobtomlinson** [comment]
That could work! I'll look into it.

**Comment by lostmygithubaccount** [comment]
close in favor of #154

**Comment by jacobtomlinson** [comment]
Do you favour generic Azure VM support over AzureML all together?

**Comment by lostmygithubaccount** [comment]
@jacobtomlinson yes, should be more stable, maintainable, and hopefully faster

**Pull request closed without merging**
