### PR TITLE
Replace master with main

### PR DESCRIPTION
**Pull request by jsignell**

### CODE REVIEW

**Review by jacobtomlinson — CHANGES_REQUESTED** [review]
Very much up for making the switch to `main` as the default branch here.

However, all the changes here are in references to dependencies (`pypa/gh-action-pypi-publish` and `python-versioneer/python-versioneer`) which still use `master` and therefore are not valid.

**Comment by jacobtomlinson** [comment]
Given the versioneer ones are just in comments there isn't really any harm in changing them.

**Comment by jsignell** [comment]
:facepalm: I didn't look close enough at the github action.

**Review by jacobtomlinson — APPROVED** [review]

**Comment by jacobtomlinson** [comment]
Thanks @jsignell

**Pull request merged**
