### PR TITLE
[Dask] Add support for AWS Fargate Spot clusters

### PR DESCRIPTION
**Pull request by dirtyValera**
Runs Workers on `FARGATE_SPOT` and Scheduler on `FARGATE` capacity providers if `FargateCluster(fargate_spot=True)`

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
Thanks for raising this. 

Could you share a little on the decision to add `fargate_capacity_provider` and `fargate_spot` kwargs and what the difference is?

Also it looks like linting is failing.

**Comment by dirtyValera** [comment]
> Thanks for raising this.
> 
> Could you share a little on the decision to add `fargate_capacity_provider` and `fargate_spot` kwargs and what the difference is?
> 
> Also it looks like linting is failing.

`fargate_spot` indicates a cluster level configuration: scheduler on `FARGATE` and workers on `FARGATE_SPOT` capacity providers. Since it is a cluster logic, I didn't pass the flag down to workers (`FARGATE` vs `FARGATE_SPOT` decision is made outside `Task` class).

`fargate_capacity_provider` is a capacity provider specific for `fargate_spot=True` configuration since it is set only when tasks run on Fargate Spot. I didn't generalize to setting arbitrary capacity provider to make sure it's not a breaking change (e.g. https://github.com/dask/dask-cloudprovider/issues/261, some people already pass down capacity providers in kwargs, I wanted to keep it as it is, defaulting to `fargate_spot=False`)

**Comment by jacobtomlinson** [comment]
Thanks @dirtyValera could you update the docstrings to make it clear how the two options interact?

**Comment by dirtyValera** [comment]
> Thanks @dirtyValera could you update the docstrings to make it clear how the two options interact?

Updated

**Review by jacobtomlinson — APPROVED** [review]
Much appreciated!

**Comment by tracek** [comment]
Hey @dirtyValera - I was wondering if you know if I might be doing something incorrectly when trying to use this nice feature you have implemented: https://github.com/dask/dask-cloudprovider/issues/328 ? Is this something you can repro or is it just me? If it's general, I could try to fix it & PR. Maybe you already have a good idea what could be the issue?

**Pull request merged**
