### PR TITLE
Configure scheduler internal/external ip with public_ingress option

### PR DESCRIPTION
**Pull request by quasiben**
Resolves https://github.com/dask/dask-cloudprovider/issues/161

cc @eric-czech

### CODE REVIEW

**Comment by eric-czech** [comment]
🙏  @quasiben

**Comment by quasiben** [comment]
@jacobtomlinson was able to launch a cluster in 3 minutes after generating a machine image with packer and baking in the docker image to the machine image.  My guess is that he'll have [additional instructions](https://cloudprovider.dask.org/en/latest/packer.html) up for this later this week

**Comment by jacobtomlinson** [comment]
Should we also be setting some config somewhere for `GCPCluster` to not request a public IP address.

In here perhaps?

https://github.com/dask/dask-cloudprovider/blob/fcedd96ed173ba5c1a77fa35d6ac48787e44fb2e/dask_cloudprovider/gcp/instances.py#L108-L122

**Comment by quasiben** [comment]
> Should we also be setting some config somewhere for GCPCluster to not request a public IP address.
In here perhaps?

Yes -- addressed in 8dd3789

**Pull request merged**
